# Generated by Django 3.2.25 on 2025-03-12 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Miembro del personal')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios_personalizados', to='auth.Group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios_personalizados', to='auth.Permission', verbose_name='Permisos de Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=100, verbose_name='Nombre del Plato')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cantidad_disponible', models.IntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('recomendado', models.BooleanField(default=False, verbose_name='Recomendado')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Imagen del Plato')),
            ],
        ),
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Recarga')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recarga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('codigo_recogida', models.CharField(max_length=10, unique=True, verbose_name='Código de Recogida')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del Pedido')),
                ('estado_pedido', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10, verbose_name='Estado del Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.menu', verbose_name='Producto')),
            ],
        ),
    ]
